# Generated by Django 3.2.16 on 2024-09-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_newuser_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='follower',
            new_name='user',
        ),
    ]
