version: '3.3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    container_name: foodgram-frontend
    build: ./frontend/
    volumes:
      - static:/frontend_static/
    command: cp -r /app/build/. /frontend_static/

  backend:
    container_name: foodgram-backend
    env_file: .env
    build: ./backend/
    volumes:
      - static:/backend_static/
      - media:/app/media/
   
  gateway:
    container_name: foodgram-gateway
    image: nginx:1.25.4-alpine
    build: ./infra/
    ports:
      - 80:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - ./docs/:/staticfiles/api/docs/
      - media:/media/
 