# Generated by Django 3.2.16 on 2024-09-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240926_0000'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingсart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes _ shoppingсart _unique_relationships'),
        ),
    ]
