# Generated by Django 3.2.16 on 2024-09-26 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_alter_recipe_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingСart',
            new_name='ShoppingCart',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='recipes _ shoppingсart _unique_relationships',
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='recipes _ shoppingcart _unique_relationships'),
        ),
    ]
