# Generated by Django 3.2.16 on 2024-07-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='IngredientInRecipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Shopping_cart',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
