# Generated by Django 3.2.16 on 2024-07-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredientinrecipe_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='receipe',
            new_name='recipe',
        ),
    ]
