# Generated by Django 3.2.16 on 2024-08-27 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0016_auto_20240827_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='author',
        ),
        migrations.AddField(
            model_name='favorite',
            name='current_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, добавляющий рецепт в избранное'),
        ),
    ]
