# Generated by Django 3.2.16 on 2024-08-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20240827_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='current_user',
            new_name='user',
        ),
    ]
