# Generated by Django 3.2.16 on 2024-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_shortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='short_link',
        ),
        migrations.AddField(
            model_name='shortlink',
            name='short_code',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
    ]
