# Generated by Django 3.2.16 on 2024-08-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20240831_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='original_path',
            field=models.CharField(max_length=300),
        ),
    ]
