# Generated by Django 3.2.16 on 2024-08-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_shortlink_original_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='original_path',
            field=models.URLField(max_length=300),
        ),
    ]
